### ISSUE TITLE
Cancelling?

### ISSUE THREAD

**Issue by PySimpleGUI** [dillanthumous/dungeondrafttagmaker#1]
While I've not run the code yet, I did scan through it.  It's NOT some terrible mess of code as you're claiming in the readme.  I quickly found the GUI and was able to read it with zero problems.  You've written fine code.

What seems to be missing is the check for the cancel button.  You go ahead and process everything without checking to see if the user cancelled.  If it's not need, then you can delete the button. 

I would recommend adding a check for `event == sg.WIN_CLOSED` along with the cancel.  So maybe this line:
```python
if event == sg.WIN_CLOSED or event == 'Cancel':
    sg.popup('Cancelling operation')
    exit()
```

Because your window is a "one-shot" and you will not interact with it after the read returns, add the `close=True` parameter to your `Window` call.  This will allow you to remove the `window.close()` call as the window will automatically close after being read if using this parameter.

Nice job of not only making this, but also putting screenshots in the readme file.  Very professional looking as a result!

**Comment by dillanthumous** [comment]
> Nice job of not only making this, but also putting screenshots in the readme file. Very professional looking as a result!

Thanks for the advice, will have a look and implement those tweaks to catch the cancel button. First time trying PySimpleGUI - it is excellent, and after 2 hours of head scratching with TKinter it is a pleasure to use instead. 

As I said in my notes, relatively new to coding so a bit paranoid that I am writing garbage half the time - so I appreciate the kind words :D

**Comment by PySimpleGUI** [comment]
Your code doesn't look like you're new to coding to me.  It's neatly formatted.  I don't see any of the normal beginner mistakes.  You've got comments that you added (versus copying from someone else's code).  It's clear to me that you've got "the knack" that's required to be a good programmer.  I really encourage you to keep learning.  

Because your window is a "one-shot" window, that is to say that you are reading it once and only once, then you don't need to hang onto the window object itself.  You can combine 3 of your lines of code into 1 line:

```python
window = sg.Window('Dungeon Draft Tag Generator - Uses Folder Names to Make Your Tags', layout)    
event, values = window.read() # Capture then inputs    
window.close() # Get rid of window
```

becomes

```python
event, values = sg.Window('Dungeon Draft Tag Generator - Uses Folder Names to Make Your Tags', layout).read(close=True)
```

That line of code creates a Window and then immediately reads it.  It will automatically close the window because of the `close` parameter being set to `True`

---------------------------


It's always good to hear from complete beginners what the learning process was like.

Is there anything the was difficult for you to grasp initially or could have been mentioned earlier than it is in the documentation or elsewhere that would have been helpful to know sooner?

tkinter is more than a head-scratcher for a beginner.  If you've only had a couple of weeks of Python programming, it's an impossibility.  OOP isn't something you pick up in n afternoon on your first few weeks of programming.

Hopefully PySimpleGUI's made it possible to do something you might not have been able to do before.

**Comment by dillanthumous** [comment]
Thanks for the quick reply (and detail on that change) - I had already implemented based on your previous suggestion and seems to be working as intended now. 

Have left the window as a separate variable for my own sanity as, if I have to come back later, the one-liner will probably confuse me.

Learning coding in eaarnest has been interesting - I have bounced off it multiple times in the last couple of years (I work in Ops and have always been techy, but aside from Excel Macros had no reason to code).

I only really started really plugging away at it this year though. Working through CS50 and 6.00x on EdX have been game changers as I feel like they really hammer home the importance of understanding the concepts first - rather than the myriad code-along tutorials and courses that I feel like are only working now that I somewhat understand what the hell is going on. 

Also, writing code in Python or even C# in Unity feels dreamlike after starting with C in CS50 - so I definitely appreciate the syntactic sugar, and also the glut of incredible modules (like your one) that make life sooo much easier.

With Tkinter I basically had got it all working, but it was extremely ugly, both on the UI side and in the code - so you have made programming this not only easier, but 100% more pleasant.

Again, I appreciate the encouragement hugely. And the advice on improving the code of course.

**Comment by PySimpleGUI** [comment]
Nicely done.

![image](https://user-images.githubusercontent.com/46163555/81604970-bd674900-939e-11ea-99fe-72234b4f1d93.png)


Yea, I agree with keeping window separate and like that you went with the close parameter on the read.  That's understandable for a beginner.  "Chained" calls are confusing for beginners.  It's why I made "finalize" a parameter inside of continuing to force people to either call the `finalize` method or chaining `finalize` onto the end of creating a window.

You might be the first piece of code PySimpleGUI code on GitHub that's using the `WIN_CLOSED` variable.  It's about as new as they come.... but it's the future of PySimpleGUI so nice job dropping it in.  Be aware that it requires version 4.19.0 and beyond in order for that constant to be present.  IT's a sneaky way of me getting people to upgrade their PySimpleGUI if they want to use one of the demo programs now.

Glad to be of help / encouragement.  Making stuff is THE way to learn. Keep making things and you'll not only end up with things you can use, but you'll learn/grow at the same time.  You're off to an excellent start.  I HATED GUI programming my entire life.  It wasn't until  PySimpleGUI made it practically trivial that I fell in love with it.  It's also the first time I've been able to make programs for myself versus someone else.

**Comment by PySimpleGUI** [comment]
BTW, thank you for mentioning CS50.  I had heard about the course from a friend but didn't know anything about it.  Now I followed up and read a little about it.

https://www.edx.org/course/cs50s-introduction-to-computer-science

Impressed at your discipline.  I was downvoted heavily on Reddit recently for suggesting someone learn by taking a university course.  It's a weird place when you're boo'd for suggesting that a formal education is a good thing.  If it's not a YouTube one and done tutorial, there seems to be no appetite for it now.  Glad to see someone that's going it a little more traditionally.  Your code shows it.

**Comment by dillanthumous** [comment]
No worries at all - by the way, the Demo snippets you made using your code super-easy. So kudos on that - a lot of man-page type documentation is a still confusing to me as they tend to presume you can create your own concrete versions from the more abstract examples they give - whereas having the screenshots right next to the code and a clear and simple example in front of me made it far simpler to get up and running quickly.

As for the university approach to learning, I am that kind of person - I hate using things I don't fully understand - and when I first started coding (and gave up) I fell into the trap of just copy pasting without really knowing why things did (or more often didn't) work. Which was wholly unsatisfying. 

I'm surprised you got so much hate for it to be honest, I would have thought it was the more sensible way to go... then again, we do live in a bit of a "lift yourself up by your bootstraps" world these days, and people are inherently suspicious of traditional methods as a result.

Can't recommend CS50 enough for CS basics. And the MIT 6.01x is great for just getting straight into using Python. Just about to try the CS50 follow ups on Gaming (using LUA) and Web Dev (using Python).
